"""add metric domain tables (checkins, niggles, mini_tests, daily_metrics, feedbacks, illness_flags)

Revision ID: d48d92815ec6
Revises: 1338813033fe
Create Date: 2026-06-04 00:11:32.612600

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d48d92815ec6"
down_revision: str | None = "1338813033fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_checkins",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("form_vs_normal", sa.Integer(), nullable=False),
        sa.Column("motivation", sa.Integer(), nullable=False),
        sa.Column("fatigue", sa.Integer(), nullable=False),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_to_coachagent", sa.Boolean(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("fatigue >= 1 AND fatigue <= 5", name="ck_daily_checkins_fatigue"),
        sa.CheckConstraint(
            "form_vs_normal >= -2 AND form_vs_normal <= 2", name="ck_daily_checkins_form_vs_normal"
        ),
        sa.CheckConstraint(
            "motivation >= 1 AND motivation <= 5", name="ck_daily_checkins_motivation"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_daily_checkins_user_date"),
    )
    with op.batch_alter_table("daily_checkins", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_daily_checkins_user_id"), ["user_id"], unique=False)

    op.create_table(
        "daily_metrics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("sleep_score", sa.Integer(), nullable=True),
        sa.Column("sleep_duration_min", sa.Integer(), nullable=True),
        sa.Column("sleep_onset", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sleep_wake", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hrv_rmssd", sa.Float(), nullable=True),
        sa.Column(
            "hrv_status",
            sa.Enum("low", "normal", "high", name="hrvstatus", native_enum=False),
            nullable=True,
        ),
        sa.Column("rhr", sa.Integer(), nullable=True),
        sa.Column("stress", sa.Integer(), nullable=True),
        sa.Column("body_battery", sa.Integer(), nullable=True),
        sa.Column("resp_rate", sa.Float(), nullable=True),
        sa.Column("training_readiness", sa.Integer(), nullable=True),
        sa.Column("vo2max", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_daily_metrics_user_date"),
    )
    with op.batch_alter_table("daily_metrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_daily_metrics_user_id"), ["user_id"], unique=False)

    op.create_table(
        "illness_flags",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("symptoms", sa.JSON(), nullable=False),
        sa.Column("watch_hint_triggered", sa.Boolean(), nullable=False),
        sa.Column("confirmed_by_user", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_illness_flags_user_date"),
    )
    with op.batch_alter_table("illness_flags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_illness_flags_user_id"), ["user_id"], unique=False)

    op.create_table(
        "mini_tests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "type",
            sa.Enum("jump", "reaction", name="minitesttype", native_enum=False),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mini_tests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mini_tests_user_id"), ["user_id"], unique=False)

    op.create_table(
        "niggles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("opened_at", sa.Date(), nullable=False),
        sa.Column("closed_at", sa.Date(), nullable=True),
        sa.Column(
            "region",
            sa.Enum(
                "foot_fore",
                "foot_mid",
                "foot_heel",
                "ankle",
                "achilles",
                "calf",
                "shin",
                "knee_anterior",
                "knee_medial",
                "knee_lateral",
                "knee_posterior",
                "quad",
                "hamstring",
                "adductor",
                "it_band",
                "hip_flexor",
                "glute",
                "groin",
                "lower_back",
                "upper_back",
                "neck",
                "shoulder",
                "other",
                name="bodyregion",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "side",
            sa.Enum("left", "right", "center", "bilateral", name="side", native_enum=False),
            nullable=False,
        ),
        sa.Column("structure", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("niggles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_niggles_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_niggles_user_id_closed_at", ["user_id", "closed_at"], unique=False
        )

    op.create_table(
        "session_feedbacks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("activity_id", sa.String(length=64), nullable=False),
        sa.Column("rpe", sa.Integer(), nullable=False),
        sa.Column(
            "affect",
            sa.Enum("weak", "neutral", "strong", name="affect", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("garmin_watch", "app_manual", name="feedbacksource", native_enum=False),
            nullable=False,
        ),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_to_coachagent", sa.Boolean(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rpe >= 1 AND rpe <= 10", name="ck_session_feedbacks_rpe"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "activity_id", name="uq_session_feedbacks_user_activity"),
    )
    with op.batch_alter_table("session_feedbacks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_feedbacks_user_id"), ["user_id"], unique=False)

    op.create_table(
        "niggle_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("niggle_id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("intensity", sa.Integer(), nullable=False),
        sa.Column(
            "pain_type",
            sa.Enum(
                "sharp",
                "dull",
                "tension",
                "burning",
                "stabbing",
                name="paintype",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "mechanical_pattern",
            sa.Enum(
                "uphill",
                "downhill",
                "push_off",
                "impact",
                "rest",
                "constant",
                name="mechanicalpattern",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "timing",
            sa.Enum(
                "during", "after", "morning_stiffness", "constant", name="timing", native_enum=False
            ),
            nullable=True,
        ),
        sa.Column("is_new_or_recurrent", sa.String(length=20), nullable=False),
        sa.Column("linked_activity_id", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "intensity >= 0 AND intensity <= 10", name="ck_niggle_reports_intensity"
        ),
        sa.ForeignKeyConstraint(["niggle_id"], ["niggles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("niggle_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_niggle_reports_niggle_id"), ["niggle_id"], unique=False
        )

    # Expression-based (DESC) composite indexes — added manually because
    # autogenerate cannot reflect/compare expression indexes on SQLite.
    op.create_index(
        "ix_daily_checkins_user_id_date",
        "daily_checkins",
        ["user_id", sa.text("date DESC")],
        unique=False,
    )
    op.create_index(
        "ix_daily_metrics_user_id_date",
        "daily_metrics",
        ["user_id", sa.text("date DESC")],
        unique=False,
    )
    op.create_index(
        "ix_illness_flags_user_id_date",
        "illness_flags",
        ["user_id", sa.text("date DESC")],
        unique=False,
    )
    op.create_index(
        "ix_mini_tests_user_id_type_date",
        "mini_tests",
        ["user_id", "type", sa.text("date DESC")],
        unique=False,
    )
    op.create_index(
        "ix_niggles_user_id_opened_at",
        "niggles",
        ["user_id", sa.text("opened_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_niggle_reports_niggle_id_date",
        "niggle_reports",
        ["niggle_id", sa.text("date DESC")],
        unique=False,
    )
    op.create_index(
        "ix_session_feedbacks_user_id_reported_at",
        "session_feedbacks",
        ["user_id", sa.text("reported_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_session_feedbacks_user_id_reported_at", table_name="session_feedbacks")
    op.drop_index("ix_niggle_reports_niggle_id_date", table_name="niggle_reports")
    op.drop_index("ix_niggles_user_id_opened_at", table_name="niggles")
    op.drop_index("ix_mini_tests_user_id_type_date", table_name="mini_tests")
    op.drop_index("ix_illness_flags_user_id_date", table_name="illness_flags")
    op.drop_index("ix_daily_metrics_user_id_date", table_name="daily_metrics")
    op.drop_index("ix_daily_checkins_user_id_date", table_name="daily_checkins")
    with op.batch_alter_table("niggle_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_niggle_reports_niggle_id"))

    op.drop_table("niggle_reports")
    with op.batch_alter_table("session_feedbacks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_feedbacks_user_id"))

    op.drop_table("session_feedbacks")
    with op.batch_alter_table("niggles", schema=None) as batch_op:
        batch_op.drop_index("ix_niggles_user_id_closed_at")
        batch_op.drop_index(batch_op.f("ix_niggles_user_id"))

    op.drop_table("niggles")
    with op.batch_alter_table("mini_tests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mini_tests_user_id"))

    op.drop_table("mini_tests")
    with op.batch_alter_table("illness_flags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_illness_flags_user_id"))

    op.drop_table("illness_flags")
    with op.batch_alter_table("daily_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_metrics_user_id"))

    op.drop_table("daily_metrics")
    with op.batch_alter_table("daily_checkins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_checkins_user_id"))

    op.drop_table("daily_checkins")
    # ### end Alembic commands ###
